import { readFileSync, existsSync } from "node:fs";
import { path } from "zx";
import { parseDocument } from "yaml";
import { avmConfigFile } from "./config.ts";

// ---------- Types ----------

export interface AvmConfig {
  volumes: VolumeMount[];
  repos: Record<string, RepoConfig>;
}

export interface VolumeMount {
  /** Raw source string as written in config.yaml (relative to ~/.avm/volumes/ unless absolute). */
  source: string;
  /** Raw target string as written in config.yaml (relative to /home/agent/ unless absolute; ~/ expands to /home/agent/). */
  target: string;
}

export interface RepoConfig {
  symlinks: SymlinkMount[];
}

export interface SymlinkMount {
  /** Raw source, relative to ~/.avm/files/. */
  source: string;
  /** Raw target, relative to the avm-link invocation cwd (typically a repo working copy). */
  target: string;
}

// ---------- Public API ----------

/**
 * Load and validate `~/.avm/config.yaml`. Returns an empty config if the
 * file does not exist. Throws on schema errors with a message that
 * identifies the offending key.
 */
export function loadAvmConfig(): AvmConfig {
  if (!existsSync(avmConfigFile)) {
    return { volumes: [], repos: {} };
  }
  const raw = readFileSync(avmConfigFile, "utf-8");
  return parseAvmConfig(raw);
}

/** Parse + validate YAML content. Separated from I/O for testability. */
export function parseAvmConfig(yamlSource: string): AvmConfig {
  const doc = parseDocument(yamlSource);
  if (doc.errors.length > 0) {
    const msg = doc.errors.map((e) => e.message).join("\n");
    throw new Error(`Invalid YAML in ${avmConfigFile}:\n${msg}`);
  }
  const data = (doc.toJS() ?? {}) as unknown;
  return validate(data);
}

/**
 * Generate the bash source of `/usr/local/bin/avm-link` from a loaded config.
 * The script dispatches on `$1` (or `$(basename "$PWD")`) and applies the
 * symlinks declared for that repo. Repos not in the config are a no-op.
 */
export function generateAvmLinkScript(config: AvmConfig): string {
  const lines: string[] = [
    "#!/bin/bash",
    "# Generated by avm — do not edit",
    "set -e",
    'repo="${1:-$(basename "$PWD")}"',
    'case "$repo" in',
  ];

  for (const [repoName, repoConfig] of Object.entries(config.repos)) {
    lines.push(`  ${repoName})`);
    for (const link of repoConfig.symlinks) {
      const src = `$HOME/.avm-files/${link.source}`;
      const parent = path.dirname(link.target);
      if (parent !== "." && parent !== "/") {
        lines.push(`    mkdir -p "${parent}"`);
      }
      lines.push(`    ln -sf "${src}" "${link.target}"`);
    }
    lines.push("    ;;");
  }

  lines.push("  *)");
  lines.push("    exit 0");
  lines.push("    ;;");
  lines.push("esac");
  lines.push("");

  return lines.join("\n");
}

// ---------- Validation ----------

const TOP_LEVEL_KEYS = new Set(["volumes", "repos"]);
const REPO_KEYS = new Set(["symlinks"]);

function validate(data: unknown): AvmConfig {
  if (data === null || typeof data !== "object" || Array.isArray(data)) {
    throw new Error(
      `${avmConfigFile}: top-level must be a mapping (got ${describe(data)}).`,
    );
  }

  const obj = data as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    if (!TOP_LEVEL_KEYS.has(key)) {
      throw new Error(
        `${avmConfigFile}: unknown top-level key "${key}". Allowed: ${[...TOP_LEVEL_KEYS].join(", ")}.`,
      );
    }
  }

  const volumes = parseVolumes(obj.volumes);
  const repos = parseRepos(obj.repos);
  return { volumes, repos };
}

function parseVolumes(raw: unknown): VolumeMount[] {
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "volumes" must be a list (got ${describe(raw)}).`,
    );
  }
  return raw.map((entry, i) => {
    if (typeof entry !== "string") {
      throw new Error(
        `${avmConfigFile}: volumes[${i}] must be a "source:target" string (got ${describe(entry)}).`,
      );
    }
    return splitShortForm(entry, `volumes[${i}]`);
  });
}

function parseRepos(raw: unknown): Record<string, RepoConfig> {
  if (raw === undefined) return {};
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "repos" must be a mapping (got ${describe(raw)}).`,
    );
  }
  const out: Record<string, RepoConfig> = {};
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      throw new Error(
        `${avmConfigFile}: repos.${name} must be a mapping (got ${describe(value)}).`,
      );
    }
    const repoObj = value as Record<string, unknown>;
    for (const key of Object.keys(repoObj)) {
      if (!REPO_KEYS.has(key)) {
        throw new Error(
          `${avmConfigFile}: unknown key "${key}" under repos.${name}. Allowed: ${[...REPO_KEYS].join(", ")}.`,
        );
      }
    }
    out[name] = { symlinks: parseSymlinks(repoObj.symlinks, name) };
  }
  return out;
}

function parseSymlinks(raw: unknown, repoName: string): SymlinkMount[] {
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: repos.${repoName}.symlinks must be a list (got ${describe(raw)}).`,
    );
  }
  return raw.map((entry, i) => {
    if (typeof entry !== "string") {
      throw new Error(
        `${avmConfigFile}: repos.${repoName}.symlinks[${i}] must be a "source:target" string (got ${describe(entry)}).`,
      );
    }
    return splitShortForm(entry, `repos.${repoName}.symlinks[${i}]`);
  });
}

/** Split "source:target" on the first colon. Both sides must be non-empty. */
function splitShortForm(
  entry: string,
  context: string,
): { source: string; target: string } {
  const idx = entry.indexOf(":");
  if (idx === -1) {
    throw new Error(
      `${avmConfigFile}: ${context} ("${entry}") must be "source:target".`,
    );
  }
  const source = entry.slice(0, idx);
  const target = entry.slice(idx + 1);
  if (source.length === 0 || target.length === 0) {
    throw new Error(
      `${avmConfigFile}: ${context} ("${entry}") has an empty source or target.`,
    );
  }
  return { source, target };
}

function describe(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "list";
  return typeof value;
}
