import { readFileSync, writeFileSync, mkdirSync, renameSync } from "node:fs";
import { dirname } from "node:path";
import { avmSshConfigFile } from "./config.ts";
import { listAvmVms, type VmInfo } from "./vm.ts";

const MANAGED_BANNER =
  "# Managed by avm. Do not edit — regenerated by `avm ssh-config sync`.";

/** Render the full contents of `~/.avm/ssh_config` from the given VMs. */
export function renderManagedFile(vms: VmInfo[]): string {
  const blocks: string[] = [];
  for (const vm of vms) {
    if (vm.sshPort == null) continue;
    blocks.push(
      [
        `Host ${vm.name}`,
        `  HostName localhost`,
        `  Port ${vm.sshPort}`,
        `  User agent`,
        `  StrictHostKeyChecking no`,
        `  UserKnownHostsFile /dev/null`,
      ].join("\n"),
    );
  }
  const body = blocks.length > 0 ? blocks.join("\n\n") + "\n" : "";
  return `${MANAGED_BANNER}\n\n${body}`;
}

/** Write `~/.avm/ssh_config` from the current set of avm containers. */
export async function syncSshConfig(): Promise<void> {
  const vms = await listAvmVms();
  const contents = renderManagedFile(vms);
  mkdirSync(dirname(avmSshConfigFile), { recursive: true });
  const tmp = `${avmSshConfigFile}.tmp`;
  writeFileSync(tmp, contents, { mode: 0o644 });
  renameSync(tmp, avmSshConfigFile);
}
