import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { path } from "zx";
import { parseDocument } from "yaml";
import { avmConfigFile } from "./config.ts";

// ---------- Types ----------

export type EditorChoice = "code" | "cursor";

export interface DaemonConfig {
  port: number;
}

export interface ServiceDefinition {
  kind: "process" | "docker";
  command?: string[];
  container?: string;
  check: ServiceCheck;
}

export interface ServiceCheck {
  tcp: string;
}

export interface AvmConfig {
  editor?: EditorChoice;
  daemon: DaemonConfig;
  volumes: VolumeMount[];
  repos: Record<string, RepoConfig>;
  services: Record<string, ServiceDefinition>;
}

export interface VolumeMount {
  /** Raw source string as written in config.yaml (relative to ~/.avm/volumes/ unless absolute). */
  source: string;
  /** Raw target string as written in config.yaml (relative to /home/agent/ unless absolute; ~/ expands to /home/agent/). */
  target: string;
}

export interface RepoConfig {
  symlinks: SymlinkMount[];
}

export interface SymlinkMount {
  /** Raw source, relative to ~/.avm/files/. */
  source: string;
  /** Raw target, relative to the avm-link invocation cwd (typically a repo working copy). */
  target: string;
}

// ---------- Public API ----------

/**
 * Load and validate `~/.avm/config.yaml`. Returns an empty config if the
 * file does not exist. Throws on schema errors with a message that
 * identifies the offending key.
 */
export function loadAvmConfig(): AvmConfig {
  if (!existsSync(avmConfigFile)) {
    return { daemon: { port: 6970 }, volumes: [], repos: {}, services: {} };
  }
  const raw = readFileSync(avmConfigFile, "utf-8");
  return parseAvmConfig(raw);
}

/**
 * Set the `editor` field in `~/.avm/config.yaml`, preserving all other
 * content and formatting. Creates the file if it doesn't exist.
 */
export function setConfigEditor(editor: EditorChoice): void {
  const raw = existsSync(avmConfigFile)
    ? readFileSync(avmConfigFile, "utf-8")
    : "";
  const doc = parseDocument(raw);
  doc.set("editor", editor);
  writeFileSync(avmConfigFile, doc.toString());
}

/** Parse + validate YAML content. Separated from I/O for testability. */
export function parseAvmConfig(yamlSource: string): AvmConfig {
  const doc = parseDocument(yamlSource);
  if (doc.errors.length > 0) {
    const msg = doc.errors.map((e) => e.message).join("\n");
    throw new Error(`Invalid YAML in ${avmConfigFile}:\n${msg}`);
  }
  const data = (doc.toJS() ?? {}) as unknown;
  return validate(data);
}

/**
 * Generate the bash source of `/usr/local/bin/avm-link` from a loaded config.
 * The script dispatches on `$1` (or `$(basename "$PWD")`) and applies the
 * symlinks declared for that repo. Repos not in the config are a no-op.
 */
export function generateAvmLinkScript(config: AvmConfig): string {
  const lines: string[] = [
    "#!/bin/bash",
    "# Generated by avm — do not edit",
    "set -e",
    'repo="${1:-$(basename "$PWD")}"',
    'case "$repo" in',
  ];

  for (const [repoName, repoConfig] of Object.entries(config.repos)) {
    lines.push(`  ${repoName})`);
    for (const link of repoConfig.symlinks) {
      const src = `$HOME/.avm-files/${link.source}`;
      const parent = path.dirname(link.target);
      // skip mkdir for bare filenames (parent is ".") or root targets (parent is "/")
      if (parent !== "." && parent !== "/") {
        lines.push(`    mkdir -p "${parent}"`);
      }
      lines.push(`    ln -sf "${src}" "${link.target}"`);
    }
    lines.push("    ;;");
  }

  lines.push("  *)");
  lines.push("    exit 0");
  lines.push("    ;;");
  lines.push("esac");
  lines.push("");

  return lines.join("\n");
}

// ---------- Validation ----------

const TOP_LEVEL_KEYS = new Set(["editor", "volumes", "repos", "daemon", "services"]);
const VALID_EDITORS = new Set<string>(["code", "cursor"]);
const REPO_KEYS = new Set(["symlinks"]);

function validate(data: unknown): AvmConfig {
  if (data === null || typeof data !== "object" || Array.isArray(data)) {
    throw new Error(
      `${avmConfigFile}: top-level must be a mapping (got ${describe(data)}).`,
    );
  }

  const obj = data as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    if (!TOP_LEVEL_KEYS.has(key)) {
      throw new Error(
        `${avmConfigFile}: unknown top-level key "${key}". Allowed: ${[...TOP_LEVEL_KEYS].join(", ")}.`,
      );
    }
  }

  const editor = parseEditor(obj.editor);
  const daemon = parseDaemon(obj.daemon);
  const volumes = parseVolumes(obj.volumes);
  const repos = parseRepos(obj.repos);
  const services = parseServices(obj.services);
  return { editor, daemon, volumes, repos, services };
}

function parseEditor(raw: unknown): EditorChoice | undefined {
  if (raw === undefined) return undefined;
  if (typeof raw !== "string" || !VALID_EDITORS.has(raw)) {
    throw new Error(
      `${avmConfigFile}: "editor" must be one of: ${[...VALID_EDITORS].join(", ")} (got ${describe(raw)}).`,
    );
  }
  return raw as EditorChoice;
}

function parseVolumes(raw: unknown): VolumeMount[] {
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "volumes" must be a list (got ${describe(raw)}).`,
    );
  }
  return raw.map((entry, i) => {
    if (typeof entry !== "string") {
      throw new Error(
        `${avmConfigFile}: volumes[${i}] must be a "source:target" string (got ${describe(entry)}).`,
      );
    }
    return splitShortForm(entry, `volumes[${i}]`);
  });
}

function parseRepos(raw: unknown): Record<string, RepoConfig> {
  if (raw === undefined) return {};
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "repos" must be a mapping (got ${describe(raw)}).`,
    );
  }
  const out: Record<string, RepoConfig> = {};
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
      throw new Error(
        `${avmConfigFile}: repos.${name} — repo name must contain only letters, digits, dots, underscores, and hyphens.`,
      );
    }
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      throw new Error(
        `${avmConfigFile}: repos.${name} must be a mapping (got ${describe(value)}).`,
      );
    }
    const repoObj = value as Record<string, unknown>;
    for (const key of Object.keys(repoObj)) {
      if (!REPO_KEYS.has(key)) {
        throw new Error(
          `${avmConfigFile}: unknown key "${key}" under repos.${name}. Allowed: ${[...REPO_KEYS].join(", ")}.`,
        );
      }
    }
    out[name] = { symlinks: parseSymlinks(repoObj.symlinks, name) };
  }
  return out;
}

function parseSymlinks(raw: unknown, repoName: string): SymlinkMount[] {
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: repos.${repoName}.symlinks must be a list (got ${describe(raw)}).`,
    );
  }
  return raw.map((entry, i) => {
    if (typeof entry !== "string") {
      throw new Error(
        `${avmConfigFile}: repos.${repoName}.symlinks[${i}] must be a "source:target" string (got ${describe(entry)}).`,
      );
    }
    return splitShortForm(entry, `repos.${repoName}.symlinks[${i}]`);
  });
}

/** Split "source:target" on the first colon. Both sides must be non-empty and shell-safe. */
function splitShortForm(
  entry: string,
  context: string,
): { source: string; target: string } {
  const idx = entry.indexOf(":");
  if (idx === -1) {
    throw new Error(
      `${avmConfigFile}: ${context} ("${entry}") must be "source:target".`,
    );
  }
  const source = entry.slice(0, idx);
  const target = entry.slice(idx + 1);
  if (source.length === 0 || target.length === 0) {
    throw new Error(
      `${avmConfigFile}: ${context} ("${entry}") has an empty source or target.`,
    );
  }
  // Reject characters that would break double-quoted bash strings at avm-link runtime.
  const unsafeChars = /["$`\\]|[\x00-\x1f\x7f]/;
  if (unsafeChars.test(source) || unsafeChars.test(target)) {
    throw new Error(
      `${avmConfigFile}: ${context} ("${entry}") contains unsafe characters. source and target must not contain: " $ \` \\ or control characters.`,
    );
  }
  return { source, target };
}

const DAEMON_KEYS = new Set(["port"]);
const SERVICE_KEYS = new Set(["kind", "command", "container", "check"]);
const CHECK_KEYS = new Set(["tcp"]);
const VALID_SERVICE_KINDS = new Set(["process", "docker"]);

function parseDaemon(raw: unknown): DaemonConfig {
  if (raw === undefined) return { port: 6970 };
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "daemon" must be a mapping (got ${describe(raw)}).`,
    );
  }
  const obj = raw as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    if (!DAEMON_KEYS.has(key)) {
      throw new Error(
        `${avmConfigFile}: unknown key "${key}" under daemon. Allowed: ${[...DAEMON_KEYS].join(", ")}.`,
      );
    }
  }
  let port = 6970;
  if (obj.port !== undefined) {
    if (
      typeof obj.port !== "number" ||
      !Number.isInteger(obj.port) ||
      obj.port < 1 ||
      obj.port > 65535
    ) {
      throw new Error(
        `${avmConfigFile}: daemon.port must be an integer 1–65535 (got ${describe(obj.port)}).`,
      );
    }
    port = obj.port;
  }
  return { port };
}

function parseServices(
  raw: unknown,
): Record<string, ServiceDefinition> {
  if (raw === undefined) return {};
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error(
      `${avmConfigFile}: "services" must be a mapping (got ${describe(raw)}).`,
    );
  }
  const out: Record<string, ServiceDefinition> = {};
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
      throw new Error(
        `${avmConfigFile}: services.${name} — service name must contain only letters, digits, dots, underscores, and hyphens.`,
      );
    }
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      throw new Error(
        `${avmConfigFile}: services.${name} must be a mapping (got ${describe(value)}).`,
      );
    }
    const svcObj = value as Record<string, unknown>;
    for (const key of Object.keys(svcObj)) {
      if (!SERVICE_KEYS.has(key)) {
        throw new Error(
          `${avmConfigFile}: unknown key "${key}" under services.${name}. Allowed: ${[...SERVICE_KEYS].join(", ")}.`,
        );
      }
    }
    // kind: required
    if (svcObj.kind === undefined) {
      throw new Error(
        `${avmConfigFile}: services.${name}.kind is required.`,
      );
    }
    if (
      typeof svcObj.kind !== "string" ||
      !VALID_SERVICE_KINDS.has(svcObj.kind)
    ) {
      throw new Error(
        `${avmConfigFile}: services.${name}.kind must be one of: ${[...VALID_SERVICE_KINDS].join(", ")} (got ${describe(svcObj.kind)}).`,
      );
    }
    const kind = svcObj.kind as "process" | "docker";

    // kind-specific fields
    let command: string[] | undefined;
    let container: string | undefined;
    if (kind === "process") {
      if (svcObj.command === undefined) {
        throw new Error(
          `${avmConfigFile}: services.${name}.command is required when kind is "process".`,
        );
      }
      if (
        !Array.isArray(svcObj.command) ||
        svcObj.command.length === 0 ||
        !svcObj.command.every((c: unknown) => typeof c === "string")
      ) {
        throw new Error(
          `${avmConfigFile}: services.${name}.command must be a non-empty list of strings (got ${describe(svcObj.command)}).`,
        );
      }
      command = svcObj.command as string[];
    } else {
      // kind === "docker"
      if (svcObj.container === undefined) {
        throw new Error(
          `${avmConfigFile}: services.${name}.container is required when kind is "docker".`,
        );
      }
      if (typeof svcObj.container !== "string" || svcObj.container.length === 0) {
        throw new Error(
          `${avmConfigFile}: services.${name}.container must be a non-empty string (got ${describe(svcObj.container)}).`,
        );
      }
      container = svcObj.container;
    }

    // check: required
    if (svcObj.check === undefined) {
      throw new Error(
        `${avmConfigFile}: services.${name}.check is required.`,
      );
    }
    if (
      svcObj.check === null ||
      typeof svcObj.check !== "object" ||
      Array.isArray(svcObj.check)
    ) {
      throw new Error(
        `${avmConfigFile}: services.${name}.check must be a mapping (got ${describe(svcObj.check)}).`,
      );
    }
    const checkObj = svcObj.check as Record<string, unknown>;
    for (const key of Object.keys(checkObj)) {
      if (!CHECK_KEYS.has(key)) {
        throw new Error(
          `${avmConfigFile}: unknown key "${key}" under services.${name}.check. Allowed: ${[...CHECK_KEYS].join(", ")}.`,
        );
      }
    }
    if (checkObj.tcp === undefined) {
      throw new Error(
        `${avmConfigFile}: services.${name}.check.tcp is required.`,
      );
    }
    if (typeof checkObj.tcp !== "string" || checkObj.tcp.length === 0) {
      throw new Error(
        `${avmConfigFile}: services.${name}.check.tcp must be a non-empty "host:port" string (got ${describe(checkObj.tcp)}).`,
      );
    }

    out[name] = { kind, command, container, check: { tcp: checkObj.tcp } };
  }
  return out;
}

function describe(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "list";
  return typeof value;
}
